version: "3.7"
services:
  portainer:
    image: portainer/portainer-ce:2.20.1
    ports:
      - 9443:9443
    volumes:
        - data:/data
        - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
volumes:
  data:
