version: "3.7"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest 
    entrypoint: /opt/keycloak/bin/kc.sh start
    container_name: keycloak_app
    restart: unless-stopped
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HTTP_ENABLED=true
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://keycloak-postgres:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=password
    ports:
      - 127.0.0.1:8089:8080
    depends_on:
      keycloak-postgres:
        condition: service_healthy
    networks:
      - keycloak-network
  keycloak-postgres:
    container_name: keycloak_postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
      - POSTGRES_PORT=5432
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U keycloak -d keycloak'"] # User, Database
      interval: 5s
      timeout: 30s
      retries: 3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak-network

networks:
  keycloak-network:
    name: keycloak-network
    driver: bridge

volumes:
  postgres_data: